### ISSUE TITLE
cannot import name 'cached_download' from 'huggingface_hub' (G:\comfyui\ComfyUI_windows\python_embeded\Lib\site-packages\huggingface_hub\__init__.py)

### ISSUE THREAD

**Issue by qq175114** [chflame163/ComfyUI_LayerStyle_Advance#25]

**Comment by anilsathyan7** [comment]
Facing same issue with  huggingface-hub 0.29.3
However, it seems to work with pip install huggingface-hub==0.25.2
